openapi: 3.0.0
info:
  title: Translation Management API
  version: 1.0.0
servers:
  - url: http://localhost/api
paths:
  /translations:
    post:
      summary: Create a new translation.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                locale:
                  type: string
                translation_key:
                  type: string
                content:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
              required:
                - locale
                - translation_key
                - content
      responses:
        '201':
          description: Translation created.
  /translations/{id}:
    get:
      summary: Get a translation by ID.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Successful response.
    put:
      summary: Update a translation.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                locale:
                  type: string
                translation_key:
                  type: string
                content:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Translation updated.
  /translations/search:
    get:
      summary: Search translations by tag, key, or content.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: translation_key
          schema:
            type: string
        - in: query
          name: content
          schema:
            type: string
        - in: query
          name: tag
          schema:
            type: string
      responses:
        '200':
          description: Search results.
  /translations/export:
    get:
      summary: Export all translations.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of translations.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
